### ISSUE TITLE
Cant find signature config dashlet

### ISSUE THREAD

**Issue by pawelciesielka** [rouxemmanuel/DigitalSigning#14]
Hi, I installed everything on alfresco 5.0d -  cant find where to uplaoad and config signature.

**Comment by drisschelouati** [comment]
There must be an issue in your installation process, i have it installed on an Alfresco 5.0d and got it perfectly working. Try to reinstall on a vanilla installation.

**Comment by pawelciesielka** [comment]
But where should be the link to signature config - Admin section ?

**Comment by drisschelouati** [comment]
Well, you have to dashlets : 

- one is meant to upload, manage and configure your electronic signature,

- the other one is to manage and view the recently signed documents

**Comment by pawelciesielka** [comment]
I have just made fresh install of alfresco I can see signed documents dashlets but where is the one to upload certyficate - as shown here http://screencast.com/t/pEcJ4efBsq 
There is no error info in logs

**Comment by drisschelouati** [comment]
Man, why do you go to the site dashboard? a signature is something personnal, so obviously the dashlets are in your <strong>personnal</strong> dashboard, you should find them there

**Comment by pawelciesielka** [comment]
Ok, I have it, thank so much.
