### ISSUE TITLE
Unable to Create Digital Certificate

### ISSUE THREAD

**Issue by amet123** [rouxemmanuel/DigitalSigning#18]
Hi i am using Alfresco 5.1 in dashlet i try to add digital signature when i add all details show erro in daslet 
	
"The following technical error occurred
02150005 DerInputStream.getLength(): lengthTag=59, too big."

I Create Certificate from [Click Here](https://www.login.mtu.edu/tools/public/self_signed_ca_generator/cert.html)  For Testing 
Thanks

**Comment by rouxemmanuel** [comment]
Hello,

You have a problem with your certificate file : bad format or bad alias and/or password when you upload your certificate.

Emmanuel

**Comment by massimone73** [comment]
Hello,
try the following way:

`cd /opt`

`mkdir cert`

`cd cert`

`keytool -genkey -alias myalias -validity 1095 -keyalg RSA -keystore mykeystore.jks`

`keytool -export -rfc -alias myalias -keystore mykeystore.jks -file myapp.crt`

`keytool -importkeystore -srckeystore mykeystore.jks -srcstoretype JKS -deststoretype PKCS12 -destkeystore myapp-keystore.p12`

Import myapp-keystore.p12 in dashet.

**Comment by harked** [comment]
Hi @massimone73 . thanks for the steps. It works like a charm :+1:

**Comment by kranthi23** [comment]
I used the same for generating key but showing an error like this while importing 

 2016-07-05 16:02:54,877  ERROR [freemarker.runtime] [http-apr-8080-exec-6] Template processing error: "Expression signingKey.properties[\"dgtsgn:keyAlgorithm\"] is undefined on line 2, column 443 in org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl."
 
Expression signingKey.properties["dgtsgn:keyAlgorithm"] is undefined on line 2, column 443 in org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl.
