### ISSUE TITLE
Signature without a check or a question mark symbol

### ISSUE THREAD

**Issue by butdy** [rouxemmanuel/DigitalSigning#19]
Hi Sir Emmanuel,

I have successfully installed Digital Signing in Alfresco 5.0.d Community Edition. I can also sign pdf file without any errors. 
when its have digital signing with verified then it will show check symbol and when its haven't digital signing with verified then it will show question mark symbol.
how do I show my signature issued by my local CA certificate without displaying that the verified symbol

**Comment by rouxemmanuel** [comment]
Hello,

You have to add your CA Certificate into your Acrobat Reader's truststore and you'll see a green check symbol instead of a yellow question symbol.

Emmanuel

**Comment by butdy** [comment]
and how to make a green tick symbol does not appear when in verified, so that the symbol is replaced with the image of the signature

**Comment by butdy** [comment]
thanks sir Emmanuel for your response...
I made the picture size to 400 x 508 px, without transparent, so the green tick symbol does not appear

thanks
