### ISSUE TITLE
Cant upload .cer certificate

### ISSUE THREAD

**Issue by lourensk** [rouxemmanuel/DigitalSigning#2]
When I try to upload a .cer file, that has no private password, I get the following error:
 03200004 DER input, Integer tag error

**Comment by rouxemmanuel** [comment]
Same that issue #3 :

Hello,

Can you test with a X509 certificate generated with the following commands:
openssl genrsa -out test.key 2048
openssl req -new -key test.key -out test.csr -config /usr/ssl/openssl.cnf
openssl x509 -req -days 365 -in test.csr -signkey test.key -out test.crt
openssl pkcs12 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -export -in test.crt -inkey test.key -out test_pkcs12.pfx -name YourAlias

The certificate file will be "test_pkcs12.pfx", the alias will be "YourAlias" (you can change it on the last command) and you have set the password during the commands execution.

Regards,
Emmanuel

**Comment by lourensk** [comment]
I followed you steps and it resolved my issue.
