### ISSUE TITLE
Need to show the button in Workflow task

### ISSUE THREAD

**Issue by essadek** [rouxemmanuel/DigitalSigning#21]
Is it possible to add the button "Sign the document" in a workflow task, this will avoid the user to go through "View more actions".

**Comment by kranthi23** [comment]
have you add Sign the document in workflow tasks if you had done tell how to add

**Comment by rouxemmanuel** [comment]
Hello,

You can add the button on the workflow screen by declaring the button on the workflow content odel and then, when the user click on the "Sign" button, in the bpmn20.xml file of the workflow you sign your(s) docuent(s) by using the javascript API.

Example :
var parameters = new Object();
	parameters.keyPassword=keyPassword;
	parameters.document=document;
	parameters.destination=destination;
	parameters.reason=reason;
	parameters.location=location;
	parameters.contact=contact;
	parameters.position=position;
	parameters.field=field;
	parameters.page=page;
	parameters.locationX=locationX;
	parameters.locationY=locationY;
	parameters.marginX=marginX;
	parameters.marginY=marginY;
	parameters.height=height;
	parameters.width=width;
	parameters.depth=depth;
	parameters.pageNumber=pageNumber;
	
	digitalSigning.sign(parameters);

Regards,
Emmanuel

**Comment by minervamarco** [comment]
Hello,
can you tell me how to declare the button on the workflow content model ? 
I'm writing a workflow where the user fill some field; at the end of the  workflow it make a pdf where i want to add the image of the client sign.

Thanks
