### ISSUE TITLE
auto sign document. folder rule

### ISSUE THREAD

**Issue by daulet140** [rouxemmanuel/DigitalSigning#25]
Hello! 
I want that when i upload .pdf file to  folder this file will be auto signing. 
I make it by execute script in folder rule but when i create action with name digitalSign, digital-sign I get error msg: not bean found. how i can solve that problem.
thanks.

**Comment by daulet140** [comment]
Failure: Failed to execute script 'workspace://SpacesStore/8efcb9a0-cd73-43ba-9488-7ddd3e7e1afe': No bean named 'DigitalSigning' is defined

**Comment by rouxemmanuel** [comment]
Hi,

Can you test with "digitalSigning" API name (with a lower case "d").

Emmanuel

**Comment by FredyCarvalho** [comment]
Hello!
I installed the amp, but I need to sign the document more than once. When I sign the second time it overwrites the signature, creating a new version only one a signature.

What should I do?

**Comment by fabiogomes2012** [comment]
Hi daulet140,

I am looking for a script that do it, i need to create a rule to auto sign documents that is added to a folder.

Can you share your script?
