### ISSUE TITLE
Signing not enabled for all, even, and odd pages

### ISSUE THREAD

**Issue by bichage** [rouxemmanuel/DigitalSigning#28]
The option for signing all pages, even pages, and odd pages is not available.

The code for the menu is commented out, see below:

DigitalSigning-master/DigitalSigningShare/src/main/config/alfresco/site-webscripts/org/alfresco/modules/sign/sign.get.html.ftl

        <div class="yui-gd">
            <div class="yui-u first"><label for="${el}-page">${msg("label.page")}:</label></div>
            <div class="yui-u">
            	<select name="page" id="${el}-page">
            		<option value="first">${msg("label.first")}</option>
            		<option value="last">${msg("label.last")}</option>
            		****
            		<option value="specific">${msg("label.specific")}</option>
            	</select>
            	&nbsp;&nbsp;&nbsp;<input id="${el}-pageNumber" type="text" name="pageNumber" value="" size="3" disabled />
            </div>
         </div>

**Comment by rouxemmanuel** [comment]
Hello,

I've commented this html code because this feature is not actually implemented.

Regards,
Emmanuel
