### ISSUE TITLE
Error when uploading a .p12 file.

### ISSUE THREAD

**Issue by lourensk** [rouxemmanuel/DigitalSigning#3]
When trying to upload a .p12 certificate file( I use the alfresco SOLR certificate "1browser.p12") I get the following error:
keyAlgorithm is null. I tried changing the code to hardcode the algorithm to "sha1", but then it complains about the keyFirstValidity being null.

**Comment by rouxemmanuel** [comment]
Hello,

Can you test with a X509 certificate generated with the following commands:
openssl genrsa -out test.key 2048
openssl req -new -key test.key -out test.csr -config /usr/ssl/openssl.cnf
openssl x509 -req -days 365 -in test.csr -signkey test.key -out test.crt
openssl pkcs12 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -export -in test.crt -inkey test.key -out test_pkcs12.pfx -name YourAlias

The certificate file will be "test_pkcs12.pfx", the alias will be "YourAlias" (you can change it on the last command) and you have set the password during the commands execution.

Regards,
Emmanuel

**Comment by lourensk** [comment]
Creating a certificate this way does  indeed solve my problem.
