### ISSUE TITLE
Impossible de signer avec un certificat ChamberSign

### ISSUE THREAD

**Issue by guisup** [rouxemmanuel/DigitalSigning#34]
Bonjour, la signature fonctionne bien avec un certificat autosigné mais impossible de charger un certificat ChamberSign pourtant bien valide et de type "Non-répudiation" et en récupérant le bon Alias associé.

Voici les logs:

"12:18:02,823 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] Exception from executeScript - redirecting to status template error: 03120021 Wrapped Exception (with status template): 03120036 Erreur lors du traitement du modèle 'Expression signingKey.properties["dgtsgn:keyAlgorithm"] is undefined on line 2, column 443 in org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl.'. Veuillez contacter votre administrateur système.
org.springframework.extensions.webscripts.WebScriptException: 03120021 Wrapped Exception (with status template): 03120036 Erreur lors du traitement du modèle 'Expression signingKey.properties["dgtsgn:keyAlgorithm"] is undefined on line 2, column 443 in org/alfresco/plugin/digitalSigning/webscript/upload/upload.post.html.ftl.'. Veuillez contacter votre administrateur système."

Comment peut-on savoir s'où vient le problème?
Pour information, ChamberSign est prêt à fournir son support pour étudier le problème.

Merci pour votre réponse!

**Comment by trevrr** [comment]
Hi Guisup,
I think your issue is to do with the key Algorithm.
Try this:
```
openssl genrsa -out test.key 2048
openssl req -new -key test.key -out test.csr
openssl x509 -req -days 365 -in test.csr -signkey test.key -out test.crt
openssl pkcs12 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -export -in test.crt -inkey test.key -out test_pkcs12.pfx -name YourAlias
```

This allowed me to create a PFX file to upload with a transparent PNG file.

**Comment by rouxemmanuel** [comment]
Bonjour,

Est-il possible de disposer de la clef utilisée et qui provoque cette erreur ?

Au pire vous pouvez me l'envoyer directement à mon adresse : e.roux1@gmail.com

Cordialement,
Emmanuel

**Comment by guisup** [comment]
Bonjour,
Merci Emmanuel pour m'avoir indiqué quel alias utiliser.
Je ne saisissais pas le bon.

Fonctionne très bien sur ma version 4.2.f.

@trevrr : thanks for your quick response.
