### ISSUE TITLE
Change layout of Signature

### ISSUE THREAD

**Issue by trevrr** [rouxemmanuel/DigitalSigning#36]
I'd like to disable some of the fields to be displayed in a signature.
These would be the reason, the location and the time field of date time.
I'd love to have the uploaded png file only displayed with a name and date.
Has anyone done this yet?
This is a sample of what I mean:
![test_sig](https://cloud.githubusercontent.com/assets/3167968/25232498/780fbdec-25d3-11e7-87fd-6df99c19e44d.png)

**Comment by trevrr** [comment]
Has anyone any idea on how to accomplish this?

**Comment by trevrr** [comment]
I know that this is readily done in Acrobat / Acrobat Reader. Is this possible in the plugin? The layout must be defined somewhere?
ANY help would be greatly appreciated.

**Comment by rouxemmanuel** [comment]
Hi,

Let me update the plugin in order to set this kind of layout.

I'll come back to you once it'll be done.

Regards,
Emmanuel

**Comment by rouxemmanuel** [comment]
Hello,

Take a look of the new 1.2.0 release.

Regards,
Emmanuel
