### ISSUE TITLE
Error during document signing : {0}

### ISSUE THREAD

**Issue by Qj7** [rouxemmanuel/DigitalSigning#38]
Hello!

I successfully upload signature key and png to my alfresco (Alfresco Share v5.2.d) but when i trying sign document, i have error message: Error during document signing : {0}

I'ts will be great if u help me 
Thanks

![sign params example](https://cloud.githubusercontent.com/assets/15748889/26455520/31a1f58a-4173-11e7-9bec-46685868bf1c.png)

[alfresco.log .txt](https://github.com/rouxemmanuel/DigitalSigning/files/1029335/alfresco.log.txt)

**Comment by rouxemmanuel** [comment]
Hi,

Which version of Alfresco do you use ?

Emmanuel

**Comment by Qj7** [comment]
@rouxemmanuel Alfresco Share v5.2.d

**Comment by rouxemmanuel** [comment]
Actually, this plugin doesn't work on Alfresco 5.1 and above.

I need to modify the code. I'll come back to you once it will be done.

Emmanuel

**Comment by Qj7** [comment]
@rouxemmanuel thanks 
i need close issue now or wait when u modify code?
