### ISSUE TITLE
Unable to install AMPs with Java

### ISSUE THREAD

**Issue by zputnoky** [rouxemmanuel/DigitalSigning#39]
Dear Emmanuel,

Only registered to find some help to solve an issue. Working on a mock-up which requires Digital Signatures on documents. I tried to install the latest AMP versions with Java. Once it is done, and the Alfresco service is restarted, the menu item to sign the selected document is not visible. 
When the installation is done with the amply-amps.sh, the menu item appears, but some of our customizations are gone.

What is the preferred method of installation?

Best regards,

Zsolt Putnoky

**Comment by rouxemmanuel** [comment]
Hi,

The prefered method is to use "apply_amps.sh".

Regards,
Emmanuel

**Comment by zputnoky** [comment]
Hi Emmanuel,

I have noticed that apply_amps.sh does some houseworks and deletes some folders. We did some customization since and all those are gone after apply_amps. Also, I am getting a WQS unable to connect to repository: Not found message. We are using LDAP authentication

Best regards,

Zsolt Putnoky

**Comment by rouxemmanuel** [comment]
This issue is solved.
