### ISSUE TITLE
"Page to sign" parameter not working

### ISSUE THREAD

**Issue by lourensk** [rouxemmanuel/DigitalSigning#4]
When executing the "Sign The Document" action and I specify different parameters for "Page to sign", it always attached the signature only on the first page.

**Comment by rouxemmanuel** [comment]
Hello,

You have right, it doesn't work.
And it isn't possible to sign multiple pages of a PDF file so i'll modifiy the plugin in orer to choose the signing page between : the first, the last or choose the page number.

Regards,
Emmanuel

**Comment by rouxemmanuel** [comment]
Hello,

I've resolved this issue.

Regards,
Emmanuel
