### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by lhuguet** [rouxemmanuel/DigitalSigning#42]
hello,

I have installed Digital Signing but I don't know how configurate it and how generate a key. Can you help me ?

best regards,

lhuguet

**Comment by rouxemmanuel** [comment]
Hi,

Comment in issue #3 shows how to generate a self signed certificate.

Then you've to add the signature dashlet on each user dashboard. And on this dashlet, click on the configuration icon to add your generated certificats.

Emmanuel
