### ISSUE TITLE
instalation brakes

### ISSUE THREAD

**Issue by egobsv** [rouxemmanuel/DigitalSigning#43]
Hi,
I am using Alfresco CE 201707, after installing the DigitalSigning module  and restarting the server the installation breaks with the following error:

Error Code Information: 500 - An error inside the HTTP server which prevented it from fulfilling the request.
Error Message: 08250005 Failed to execute script 'classpath*:alfresco/site-webscripts/org/alfresco/components/dashlets/my-sites.get.js': 08250004 08250005 Failed during processing of IMAP server status configuration from Alfresco: 08250004 Unable to retrieve IMAP server status from Alfresco: 404
Server: Alfresco Spring WebScripts - v6.15.0 schema 1.000

**Comment by rouxemmanuel** [comment]
Hi,

Is there others stacktrace in your log file ?

This error doesn't seem to be linked to the digital signing module.

Emmanuel
