### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by Tikanya** [rouxemmanuel/DigitalSigning#47]
Hi, first of all - thank you for sharing this project! Could you please add support for Cyrillic fonts? I get a message that the signing was successful and the document properties are updated, but the signature on the document was not created.

**Comment by elabpro** [comment]
You can change package org.alfresco.plugin.digitalSigning.service.SigningService
Also you will need your TTF font for this.

[diff.patch.zip](https://github.com/rouxemmanuel/DigitalSigning/files/1486196/diff.patch.zip)

**Comment by Tikanya** [comment]
to elabpro:
Thanks a lot, it works great.
Большое спасибо!
