### ISSUE TITLE
Rule to move and sign more than once

### ISSUE THREAD

**Issue by npaniagua** [rouxemmanuel/DigitalSigning#49]
Hello, I have two questions:
1. To add a rule that moves the document after signing, which should be indicated; because if you try to indicate that it is a document that is updated generates an error and can not sign.
2. Is it possible to sign a document more than once? and if it is possible that you have to configure it.

**Comment by rouxemmanuel** [comment]
Hello,

1- You must add a rule which executes a JS file and in this JS file use the javascript API to sign the "document". You'll have to set the "destination" parameter which is the nodeRef of the folder to copy the signed document.
2- You can't sign more than once a document. Let me see how to enable this feature and go back to you.

Regards,
Emmanuel

**Comment by rouxemmanuel** [comment]
Hi,

New 1.2.1 version allows to sign more than once a document.

Regards,
Emmanuel

**Comment by npaniagua** [comment]
Thanks for your reply, I will try the new version and try to add the file using the javascript API.

regards

**Comment by FredyCarvalho** [comment]
Hello!
I installed the amp lasted, but I need to sign the document more than once. When I sign the second time it overwrites the signature, creating a new version only one a signature.

What should I do?

**Comment by FredyCarvalho** [comment]
Hello!
I installed amp 1.2.1, but I need to sign the document more than once. When I sign the second time it creates a new version with only the last signature.

What should I do?

Thank you
