### ISSUE TITLE
not showing sign on the document.

### ISSUE THREAD

**Issue by monicakumari** [rouxemmanuel/DigitalSigning#51]
I have applied amps on vanila installation(201707). and started alfresco.
uploaded the key file and sign image through create/modify signature on dashlet.

I have uploaded a test pdf file and tried to " sign the document". I got popup/showing message that "Document was successfully signed".

I opened the document there was no signature on it. **signed document is not showing any signature** on it.

**STEP 1**
![screenshot from 2018-01-10 13-36-04](https://user-images.githubusercontent.com/26789477/34761964-f1189cdc-f60b-11e7-9ab9-8aceb59860e2.png)

**step 2**
![screenshot from 2018-01-10 13-37-42](https://user-images.githubusercontent.com/26789477/34761998-1a91339e-f60c-11e7-87d8-b597f0f618f4.png)

**step 3** - showing the message.

![screenshot from 2018-01-10 13-39-11](https://user-images.githubusercontent.com/26789477/34762021-30938a7a-f60c-11e7-9a42-8ee63d2904cc.png)

**step 4** - document is signed - showing the icon. but not showing any signature on it. 
![screenshot from 2018-01-10 13-39-47](https://user-images.githubusercontent.com/26789477/34762049-5645a4c4-f60c-11e7-861a-5ff64e33eee4.png)

do you have any idea, why this is happening ?

thanks in advance.

**Comment by monicakumari** [comment]
thank you. I am able to see the signature only on downloaded document. It cannot be seen on alfresco. 

I need your help in understanding the use of the fields in attached screenshot.
what should I write in the field for properties  -  "Field", "Location X", "Location Y", "X margin" and "Y margin".

![screenshot from 2018-01-10 15-41-53](https://user-images.githubusercontent.com/26789477/34767303-c0ca311e-f61d-11e7-8b33-2fd41f31d117.png)


thanks.

**Comment by rouxemmanuel** [comment]
Hi,

Unfortunately, we can't see signature on Alfresco online preview (we need to download the PDF and open it in Acrobat Rearder for example).

The fields:
- "Field" : must be used if your PDF has a field name and you want to add the signature in this field name (set the name of the PDF field)
- "Location X", "Location Y", "X margin" and "Y margin" : must be used to set the signature at a specific postion in the PDF

You can also use the predefined positions such as top left, top right, center, bottom right and bottom left.

Emmanuel
