### ISSUE TITLE
DigitalSigningShare does not compile

### ISSUE THREAD

**Issue by medeiroseverton** [rouxemmanuel/DigitalSigning#55]
Hi Emmanuel,

I downloaded the project and tried to compile version 1.2.1. But it's presenting an error when compiling DigitalSigningShare and does not compile.
I was able to download the amps already compiled but they are from version 1.2.0.
It works fine but does not have multiple signatures.
What I need is for several people to sign the same document giving their respective authorizations.
Can you send me the amps link from version 1.2.1?

Thanks

**Comment by adelettouati** [comment]
Hi , 
you must add :
 <pluginRepositories>
                <pluginRepository>
                        <id>alfresco-private</id>
                        <url>https://artifacts.alfresco.com/nexus/content/groups/private</url>
                </pluginRepository>
                <pluginRepository>
                    <id>alfresco-public</id>
                        <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
                </pluginRepository>
                <pluginRepository>
                        <id>alfresco-thirdparty</id>
                        <url>https://artifacts.alfresco.com/nexus/content/repositories/thirdparty</url>
                </pluginRepository>
                <pluginRepository>
                        <id>alfresco-public-snapshots</id>
                        <url>https://artifacts.alfresco.com/nexus/content/repositories/public-snapshots</url>
                </pluginRepository>
                <pluginRepository>
                        <id>central</id>
                        <url>http://repo1.maven.org/maven2</url>
                </pluginRepository>
        </pluginRepositories>
in your pom.xml of DigitalSigningShare

**Comment by adelettouati** [comment]
Hi , 
you must add   <pluginRepositories> in your pom.xml of DigitalSigningShare  
you find it in pom.xml of DigitalSigningAlfresco
