### ISSUE TITLE
How to generate certificates for unexperienced users?

### ISSUE THREAD

**Issue by billerby** [rouxemmanuel/DigitalSigning#57]
I am evaluating this addon for a customer and finds it very useful and nicely implemented.

One thing I still really don't know is how to sell this concept to the customer since we are talking about very unexperienced users. I guess somehow we need to setup a process in their IT-department where they generate the certificats.

A problem with that is that the password will be known to the person setting it since there is no way to change it without openssl or keytool etc.

It would be nice to hear how others are managing this process in their organisation?

Regards!
/Erik

**Comment by rouxemmanuel** [comment]
Hi,

You are talking about self signed certificates ?
And in this case, you have right, the certificate password is defined by the person who create it (generally an IT department user).

But if you need to have a legal digital signature, the certificate must be bought on an authorized supplier (such as https://www.geotrust.com/). In this case, the certificate password is automatically generated during the creation and only known by the end user (user who use this certificate for signing documents).

Regards,
Emmanuel

**Comment by billerby** [comment]
Thanks! 
Of course they should buy the certificates. I was not thinking this through enough. :)

/Erik
