### ISSUE TITLE
Amps files are not Up to date

### ISSUE THREAD

**Issue by Dnhatsave** [rouxemmanuel/DigitalSigning#64]
Helo @rouxemmanuel ,

It would be nice if as you update the code you also update the amps files located in the directory /images/realeses/ , this is going to help a lot people(including me :-D ) have trouble generating amp packages with maven

**Comment by iurilimamarques** [comment]
Hello @Dnhatsave , 

Could you help me to install the DigitalSigning, please? I am getting the error "Authentication failed for https://artifacts.alfresco.com/nexus/content/groups/private/org/alfresco/alfresco-repository/5.2.f/alfresco-repository-5.2.f.jar 401 Unauthorized" when I execute mvn install in the DigitalSigningAlfresco directory.

**Comment by Dnhatsave** [comment]
Hi,

Just change the link to public like this 
https://artifacts.alfresco.com/nexus/content/groups/**public**/org/alfresco/alfresco-repository/5.2.f/alfresco-repository-5.2.f.jar

**Comment by iurilimamarques** [comment]
Hi @Dnhatsave,

Thank you very much, your comment helped so much.

**Comment by rouxemmanuel** [comment]
Hi, 

I've created the actual 1.2.1 release which contains binaries.
See https://github.com/rouxemmanuel/DigitalSigning/releases/tag/1.2.1

Regards,
Emmanuel

**Comment by aagrou** [comment]
Hello,
Please we got the error message below after installing.
Your authentication details haven't been recognized or Alfresco Content Services may not be available at this time.
Thanks,
AgrouA

**Comment by akashdubey251996** [comment]
> Hi,
> 
> I've created the actual 1.2.1 release which contains binaries.
> See https://github.com/rouxemmanuel/DigitalSigning/releases/tag/1.2.1
> 
> Regards,
> Emmanuel

Will it work for alfresco 6.2 ???
