### ISSUE TITLE
Had to modify .pom files

### ISSUE THREAD

**Issue by Gregwolf3030** [rouxemmanuel/DigitalSigning#66]
In each .pom file, there are entries for a nexus private repository. I'm sure this works for you (the developer) because you have access to that location (password protected). But it causes maven to error and fail immediately for me.

Also, the reference to repo1.maven.org is http. But when trying to run the .pom with maven, it fails because it says https is required.

After removing the two private repository references and changing the http to https (on the repo1 line) in each .pom, it runs like it is supposed to and created the amp files (and associated files/folders) as desired.

**Comment by rouxemmanuel** [comment]
Hi,

I've modified the pom.xml files.

Regards,
Emmanuel
