### ISSUE TITLE
I want to help to translate to spanish,

### ISSUE THREAD

**Issue by milanojs** [rouxemmanuel/DigitalSigning#9]
Hi, Im Juan From venezuela im using your plugin and i like to help you to add spanish version of your product cause i think that it could help more people who also speaks and writes spanish, and awesome  plugin! Thanks for doing!

PD:

**Comment by rouxemmanuel** [comment]
Hi Juan,

You can translate every i18n properties files and then send me this spanish files.
I will include them in the sources of the plugin.

Regards,
Emmanuel

**Comment by rouxemmanuel** [comment]
Hello,

You missed 3 files to translate into spanish :
- DigitalSigningAlfresco\src\main\config\alfresco\module\digitalSigning\messages\alert-messages.properties : email's subject on certificate expiration
- DigitalSigningAlfresco\src\main\config\alfresco\module\digitalSigning\templates\keyAlert_en.ftl : email's body on certificate expiration
- DigitalSigningShare\src\main\config\alfresco\site-webscripts\org\alfresco\components\dashlets\signed-documents.get.properties : dashlet to view all signed documents

Can you translate this files ?

Regards,
Emmanuel

**Comment by rouxemmanuel** [comment]
Hello @milanojs any news about the 3 missing files ?

Emmanuel

**Comment by milanojs** [comment]
Im pushing the changes at this moment!, Regards

**Comment by rouxemmanuel** [comment]
Thanks a lot, I've merged your contribution.

Emmanuel
